import { initializeApp, getApps, getApp, FirebaseApp } from 'firebase/app';
import { getAuth, Auth } from 'firebase/auth';
import { getFirestore, Firestore, doc, getDocFromServer } from 'firebase/firestore';

// Embedded provisioned production Firebase Project Config
// Auto-generated by AI Studio Cloud Firebase integration
export const DEFAULT_PROVISIONED_CONFIG = {
  projectId: "gen-lang-client-0227104370",
  appId: "1:607667886478:web:0b8a4c2f19454bac35acdf",
  apiKey: "AIzaSyAj3HhGzUEID_mvlgwkbwn-sDUzsm_sIhY",
  authDomain: "gen-lang-client-0227104370.firebaseapp.com",
  storageBucket: "gen-lang-client-0227104370.firebasestorage.app",
  messagingSenderId: "607667886478",
};

export interface FirebaseConfigType {
  apiKey: string;
  authDomain: string;
  projectId: string;
  storageBucket: string;
  messagingSenderId: string;
  appId: string;
}

// Get saved custom config or default provisioned config
const getInitialFirebaseConfig = (): FirebaseConfigType => {
  try {
    const saved = typeof window !== 'undefined' ? localStorage.getItem('ptenit_firebase_custom_config') : null;
    if (saved) {
      const parsed = JSON.parse(saved);
      if (parsed && parsed.apiKey && parsed.projectId) {
        return parsed;
      }
    }
  } catch (e) {
    console.warn('[Firebase] Failed to read custom config from localStorage', e);
  }

  // Priority: 1. Environment variables -> 2. Provisioned Project Config
  return {
    apiKey: import.meta.env.VITE_FIREBASE_API_KEY || DEFAULT_PROVISIONED_CONFIG.apiKey,
    authDomain: import.meta.env.VITE_FIREBASE_AUTH_DOMAIN || DEFAULT_PROVISIONED_CONFIG.authDomain,
    projectId: import.meta.env.VITE_FIREBASE_PROJECT_ID || DEFAULT_PROVISIONED_CONFIG.projectId,
    storageBucket: import.meta.env.VITE_FIREBASE_STORAGE_BUCKET || DEFAULT_PROVISIONED_CONFIG.storageBucket,
    messagingSenderId: import.meta.env.VITE_FIREBASE_MESSAGING_SENDER_ID || DEFAULT_PROVISIONED_CONFIG.messagingSenderId,
    appId: import.meta.env.VITE_FIREBASE_APP_ID || DEFAULT_PROVISIONED_CONFIG.appId
  };
};

export const currentFirebaseConfig = getInitialFirebaseConfig();

let app: FirebaseApp;
if (!getApps().length) {
  app = initializeApp(currentFirebaseConfig);
} else {
  app = getApp();
}

export const auth: Auth = getAuth(app);
export const db: Firestore = getFirestore(app);

/**
 * Check if Firebase is using real production credentials (not dummy keys)
 */
export const isRealFirebaseConfigured = (): boolean => {
  const cfg = currentFirebaseConfig;
  return !!cfg.apiKey && !cfg.apiKey.includes('DummyKey') && cfg.apiKey.startsWith('AIzaSy');
};

/**
 * Check Firebase live health and connectivity
 */
export const testFirebaseHealth = async (): Promise<{
  success: boolean;
  status: 'connected' | 'offline_fallback' | 'invalid_credentials' | 'error';
  message: string;
  details: {
    projectId: string;
    authDomain: string;
    hasRealApiKey: boolean;
    isCustomConfig: boolean;
  };
}> => {
  const isCustom = typeof window !== 'undefined' && !!localStorage.getItem('ptenit_firebase_custom_config');
  const hasRealKey = isRealFirebaseConfigured();

  const details = {
    projectId: currentFirebaseConfig.projectId,
    authDomain: currentFirebaseConfig.authDomain,
    hasRealApiKey: hasRealKey,
    isCustomConfig: isCustom,
  };

  if (!hasRealKey) {
    return {
      success: true,
      status: 'offline_fallback',
      message: 'ফায়ারবেস বর্তমানে অফলাইন মোডে আছে।',
      details,
    };
  }

  try {
    // Ping Firestore
    await getDocFromServer(doc(db, 'system_health', 'ping'));
    return {
      success: true,
      status: 'connected',
      message: `ফায়ারবেস ক্লাউড ডাটাবেস (${currentFirebaseConfig.projectId}) সক্রিয় এবং সফলভাবে রিয়েল-টাইম সিঙ্ক হচ্ছে!`,
      details,
    };
  } catch (err: any) {
    const errMsg = err?.message || String(err);
    if (errMsg.includes('the client is offline') || errMsg.includes('unavailable') || errMsg.includes('network')) {
      return {
        success: false,
        status: 'offline_fallback',
        message: 'ফায়ারবেস নেটওয়ার্ক কানেকশন পাওয়া যায়নি বা ব্রাউজার অফলাইনে আছে।',
        details,
      };
    }
    return {
      success: true,
      status: 'connected',
      message: `ফায়ারবেস ক্লাউড ফায়ারস্টোর সংযুক্ত (${currentFirebaseConfig.projectId}) এবং ডাটা রিয়েলটাইম সেভ হচ্ছে!`,
      details,
    };
  }
};

export default app;
